---
abstract: 'A parser for Qiime2 artifact files'
author:
  - 'Andrea Telatin <andrea@telatin.com>'
build_requires: {}
configure_requires:
  Devel::CheckBin: '0'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Qiime2-Reader
provides:
  Qiime2::Artifact:
    file: lib/Qiime2/Artifact.pm
    version: '1.00'
recommends:
  File::Which: '0'
requires:
  Capture::Tiny: '0.48'
  Carp: '1.2'
  Data::Dumper: '2.1'
  FindBin: '1.3'
  YAML::PP: '0.018'
  perl: '5.014'
resources:
  repository: https://github.com/telatin/qiime2tools
version: '1.00'
x_generated_by_perl: v5.18.2
x_serialization_backend: 'YAML::Tiny version 1.61'
